---
title: "DataDictionary"
output: html_document
date: "2023-12-17"
---
```{r}
#Library
library(dplyr)
rm(list = ls())
cat("\014")  # Clears the console
#Data ditioinary surveys
ECfinal<- read.csv("C:/Users/sara ghasem pour/GitLab/Path2/Thesis/DataCleaning/ECfinal.csv")
```

Part 1 Data dictionary to creat the basic questions Numeric and frequency


```{r}

# Removing the first 30 columns from ECfinal to remove questions  before starting the survey questions ,
# Removing childs bith to count and crate data dictionary , we can not use insertion type data(Such as date, and Birth date in our survey)
# Removing random ID and Date and time diff,
ECfinald <- ECfinal[, -c(1:30 ,37,177, 178,179)]
#remove the first row which are the questions name in the data 
ECfinald <- ECfinald[ -c(1),]


combinedfts <- data.frame()

# Loop through each column in the dataset
for (question in names(ECfinald)) {
  # Check if the column is a factor or character before creating a table
  if (is.factor(ECfinald[[question]]) || is.character(ECfinald[[question]])) {
    # Create frequency table and convert to data frame
    frequencytd <- as.data.frame(table(ECfinald[[question]]))
    # Reverse the order of the options
    frequencytd <- frequencytd[rev(seq_len(nrow(frequencytd))), ]
    # Add a column with the question name
    frequencytd$Question <- question
    
    # Combine with the main data frame using rbind
    combinedfts <- rbind(combinedfts, frequencytd)
  }
}

# add name questions an as a new column
com <- combinedfts
com$Fullquestion <- NA
for (question_abbr in names(ECfinald)) {
  for (j in 1:nrow(combinedfts)) {
    if (question_abbr == combinedfts[j,3]) {
      com[j,4] <- ECfinal[1,question_abbr]
    }
  }
}
#design the order of columns based on  head of questions, questions, 
com1<- com[,c(3,4,1,2)]

# Set seed for reproducibility
set.seed(123)  

# Function to generate unique random numbers for each Var1(head of name questions) within a Question
generaterandom <- function(n) {
  return(seq(1, n))
}

# Apply the function to each subset of the data frame (for each Question)
com1$Numeric<- ave(rep(NA, nrow(com1)), com1$Question, FUN = function(x) generaterandom(length(x)))
com1 <- com1 %>%
  mutate(Numeric = ifelse(Var1 == "Always", 5,
                          ifelse(Var1 == "Often", 4,
                                 ifelse(Var1 == "Sometimes", 3,
                                        ifelse(Var1 == "Rarely", 2,
                                               ifelse(Var1 == "Never", 1, Numeric))))))
com1 <- com1 %>%
  mutate(Numeric = ifelse(Var1 == "More than $100,000", 6,
                          ifelse(Var1 == "$75,000 - $99,999", 5,
                                 ifelse(Var1 == "$50,000 - $74,999", 4,
                                        ifelse(Var1 == "$40,000 - $49,999", 3,
                                               ifelse(Var1 == "$20,000 - $39,999", 2,
                                                     ifelse(Var1 == "Less than $20,000", 1,Numeric)))))))

com1 <- com1 %>%
  mutate(EducationNumeric = ifelse(Var1 == "Advanced degree", 5,
                                   ifelse(Var1 == "4 years college degree", 4,
                                            ifelse(Var1 == "Some college or associates degree", 3,
                                                 ifelse(Var1== "High school degree or GED", 2,
                                                        ifelse(Var1 == "Some high school", 1, Numeric))))))

com1 <- com1 %>%
  mutate(RelationshipNumeric = ifelse(Var1 == "Married", 1,
                              ifelse(Var1 == "Divorced", 2,
                                     ifelse(Var1 == "Separated", 3,
                                            ifelse(Var1 == "Widowed", 4,
                                                   ifelse(Var1 == "Never married", 5, Numeric))))))



write.csv(com1, "DataDictionarySheet1.csv", row.names = FALSE)
```

Data dictionary sheet2 to read and calculate statistic
```{r}
# Data dictionary: Continue Data dictionary,
# Define the mapping from text responses to numeric values
EClist <- c("Always" = 5, "Often" = 4, "Sometimes" =3 , "Rarely" = 2, "Never" = 1 )

# List the question columns for each category based on the names you provided
control_questions <- c("PFSQ5", "PFSQ17", "PFSQ18", "PFSQ20", "PFSQ24", "PFSQ26")
emotional_questions <- c("PFSQ25", "PFSQ21", "PFSQ22", "PFSQ15", "PFSQ13", "PFSQ2")
picky_questions <- c("CEBQ32", "CEBQ24", "CEBQ16", "CEBQ10", "CEBQ7")



#remove the first row which are the questions name in the data 
ECfinald <- ECfinald[ -c(1),]
com2<- ECfinald %>%
  mutate(
   across(all_of(control_questions), ~ as.numeric(EClist[.x]), .names = "numeric_{.col}"),
    across(all_of(emotional_questions), ~ as.numeric(EClist[.x]), .names = "numeric_{.col}"),
   across(all_of(picky_questions), ~ as.numeric(EClist[.x]), .names = "numeric_{.col}")
 ) %>%
  rowwise() %>%
  mutate(
    Control_Score = mean(c_across(starts_with("numeric_PFSQ")), na.rm = TRUE),
    Emotional_Score = mean(c_across(starts_with("numeric_PFSQ")), na.rm = TRUE),
    Picky_Score = mean(c_across(starts_with("numeric_CEBQ")), na.rm = TRUE)
  ) %>%
  ungroup()


```

```{r}
#Define the mapping from income levels to numeric

income_map <- c("Less than $20,000" = 1, 
                "$20,000 - $39,999" = 2, 
                "$40,000 - $49,999" = 3, 
                "$50,000 - $74,999" = 4, 
                "$75,000 - $99,999" = 5, 
                "More than $100,000" = 6)
#Convert text responses to numeric values and calculate mean scores for Income
com2 <- com2 %>%
  mutate(NumericIncome = income_map[income])
```

```{r}
# Define the mapping from education levels to numeric values
education_map <- c("Some high school" = 1, 
                   "High school degree or GED" = 2, 
                   "Some college or associates degree" = 3, 
                   "4 years college degree" = 4, 
                   "Advanced degree" = 5)

# Convert text responses to numeric values for Education
com2 <- com2 %>%
  mutate(NumericEducation = education_map[ed])

```

```{r}
# Define the mapping from relationship levels to numeric values
relationship_map <- c("Never married" = 5, 
                      "Married" = 1, 
                      "Divorced" = 2, 
                      "Separated" = 3, 
                      "Widowed" = 4)

# Convert text responses to numeric values for Relationship status
com2 <- com2 %>%
  mutate(NumericRelationship = relationship_map[relationship])

```



Calculate mean, mid,SD,min

```{r}

# Calculate statistics for each category
#control
control_stats <- com2 %>%
  summarise(
    Mean = mean(Control_Score, na.rm = TRUE),
    Median = median(Control_Score, na.rm = TRUE),
    Min = min(Control_Score, na.rm = TRUE),
    SD = sd(Control_Score, na.rm = TRUE)
  )
#emotional
emotional_stats <- com2 %>%
  summarise(
    Mean = mean(Emotional_Score, na.rm = TRUE),
    Median = median(Emotional_Score, na.rm = TRUE),
    Min = min(Emotional_Score, na.rm = TRUE),
    SD = sd(Emotional_Score, na.rm = TRUE)
  )
#picky eating
picky_stats <- com2 %>%
  summarise(
    Mean = mean(Picky_Score, na.rm = TRUE),
    Median = median(Picky_Score, na.rm = TRUE),
    Min = min(Picky_Score, na.rm = TRUE),
    SD = sd(Picky_Score, na.rm = TRUE)
  )

# Calculate statistics for each question
question_stats <- function(questions) {
  stats <- lapply(questions, function(question) {
    question_data <- com2[[paste0("numeric_", question)]]
    list(
      Mean = mean(question_data, na.rm = TRUE),
      Median = median(question_data, na.rm = TRUE),
      Min = min(question_data, na.rm = TRUE),
      SD = sd(question_data, na.rm = TRUE)
    )
  })
  names(stats) <- questions
  return(stats)
}

control_question_stats <- question_stats(control_questions)
emotional_question_stats <- question_stats(emotional_questions)
picky_question_stats <- question_stats(picky_questions)


#Calculate statistics for Age
control_Age <- com2 %>%
  summarise(
    Mean = mean(Age, na.rm = TRUE),
    Median = median(Age, na.rm = TRUE),
    Min = min(Age, na.rm = TRUE),
    SD = sd(Age, na.rm = TRUE)
  )

#Calculate statistics for income, education ,and marrital status
calculate_stats <- function(data_vector) {
    if (!is.numeric(data_vector)) {
        stop("Data must be numeric.")
    }
  
    stats <- list(
        Mean = mean(data_vector, na.rm = TRUE),
        Median = median(data_vector, na.rm = TRUE),
        Min = min(data_vector, na.rm = TRUE),
        SD = sd(data_vector, na.rm = TRUE)
    )
    
    return(stats)
}
# calculate statistical for income
income_stats <- calculate_stats(com2$NumericIncome)
# Calculate statistics for education
education_stats <- calculate_stats(com2$NumericEducation)
#calculate statistical for martital status
relationship_stats <- calculate_stats(com2$NumericRelationship)


# summarize without worrying about NA values


control_household <- com2 %>%
  summarise(
    Mean = mean(as.numeric(household), na.rm = TRUE),
    Median = median(household, na.rm = TRUE),
    Min = min(household, na.rm = TRUE),
    SD = sd(household, na.rm = TRUE)
  )






```



Create a list of questions table
```{r}

# Create a nested list
Surveys_CEP_stats <- list(control_question_stats = control_question_stats, emotional_question_stats=
                      emotional_question_stats,picky_question_stats=picky_question_stats)
Surveys_CEP_stats$control_Age<-control_Age
Surveys_CEP_stats$control_stats<-control_stats
Surveys_CEP_stats$emotional_stats<-emotional_stats
Surveys_CEP_stats$picky_stats<-picky_stats
Surveys_CEP_stats$income_stats<-income_stats
Surveys_CEP_stats$education_stats<-education_stats
Surveys_CEP_stats$control_household<-control_household
Surveys_CEP_stats$relationship_stats<-relationship_stats
# Create a data frame
A <- data.frame(
  Mean = numeric(),
  Median = numeric(),
  Min = numeric(),
  SD = numeric(),
  stringsAsFactors = FALSE
)
df<- data.frame(Surveys_CEP_stats)
# Assuming SurveysCEPstats is your data frame
ind <- grepl("Mean$", names(df))
a<-(df[1,ind])
A[1:length(df[1,ind]), "Mean"] <- t(df[1,ind])

ind <- grepl("Median$", names(df))
A[1:length(df[1,ind]), "Median"] <- t(df[1,ind])

ind <- grepl("Min$", names(df))
A[1:length(df[1,ind]), "Min"] <- t(df[1,ind])

ind <- grepl("SD$", names(df))
A[1:length(df[1,ind]), "SD"] <- t(df[1,ind])

# Add identifiers
identifiers <- c("PFSQ5","PFSQ17", "PFSQ18","PFSQ20", "PFSQ24", "PFSQ26", "PFSQ25",  "PFSQ21",  "PFSQ22", "PFSQ15", "PFSQ13","PFSQ2","CEBQ32","CEBQ24","CEBQ16","CEBQ10","CEBQ7","control_Age","control_stats","emotional_stats","picky_stats","income_stats","education_stats","control_household","relationship_stats")
A$Question <- identifiers
Survey<- A[,c(5,1:4)]
# Write the data frame to a CSV file
write.csv(Survey, file = "DataDictionarySheet2.csv", row.names = FALSE)

```

Sheet3 Data dictionary for measurement calculation
```{r}
install.packages("datadictionary")
library(datadictionary)

```
Measuring data , height weight and BMI

```{r}
# data dictionary for measuring data
cmeasure<- read.csv("C:/Users/sara ghasem pour/GitLab/Path2/Thesis/DataCleaning/cmeasure.csv")

dm<- create_dictionary(cmeasure)
write.csv(dm, "DataDictionarySheet3.csv", row.names = FALSE)
```
Stacking three sheets and save them as an excel file.


```{r}
install.packages("readr")
install.packages("openxlsx")

library(readr)
library(openxlsx)



# Create a new workbook
wb <- createWorkbook()

# Add sheets with data
addWorksheet(wb, "BasicQuestions")
writeData(wb, "BasicQuestions", com1)

addWorksheet(wb, "StatisticalSurveys")
writeData(wb, "StatisticalSurveys", Survey)

addWorksheet(wb, "StatisticalMeasurment")
writeData(wb, "StatisticalMeasurment", dm)

# Save as an Excel file
saveWorkbook(wb, "FinalDataDictionary.xlsx", overwrite = TRUE)


```



